# Generated by Django 2.0.7 on 2018-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourwords',
            name='adjective',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='adverb',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='noun',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='verb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
