# Generated by Django 2.0.7 on 2018-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_words', '0002_auto_20180726_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('word_type', models.IntegerField(choices=[(1, 'noun'), (2, 'adjective'), (3, 'adverb'), (4, 'verb')], default=1)),
            ],
        ),
    ]
