# Generated by Django 2.0.7 on 2018-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_words', '0004_auto_20180729_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourwords',
            name='adjective_desription',
        ),
        migrations.RemoveField(
            model_name='fourwords',
            name='adverb_desription',
        ),
        migrations.RemoveField(
            model_name='fourwords',
            name='noun_desription',
        ),
        migrations.RemoveField(
            model_name='fourwords',
            name='verb_desription',
        ),
        migrations.AddField(
            model_name='fourwords',
            name='adjective_description',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='fourwords',
            name='adverb_description',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='fourwords',
            name='noun_description',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='fourwords',
            name='verb_description',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='adjective_example',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='adverb_example',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='noun_example',
            field=models.TextField(blank=True, max_length=230),
        ),
        migrations.AlterField(
            model_name='fourwords',
            name='verb_example',
            field=models.TextField(blank=True, max_length=230),
        ),
    ]
